name: getx_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.0.0 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  fonts:
    - family: Poppins
      fonts:
        - asset: asset/Font/Poppins-Bold.ttf
  assets:
    - asset/logo.png
    - asset/image/jackets.jpg
    - asset/image/backpack.jpg
    - asset/klimjacket.jpeg
    - asset/image/kaos.png
    - asset/image/tas.jpg
    - asset/image/jakethnm.jpg
    - asset/image/celana.jpg
